### PR TITLE
Add filters to GetInventory function

### PR DESCRIPTION
**Pull request by Furdarius**

### CODE REVIEW

**Comment by asamy** [comment]
You're kind of breaking backward compatibility, we use this stuff in production code, when we update, we would also need to also update the code that uses it and that's a lot of stuff.

So, we need to kind of remove the language thing, as we already have `Steam_Language` cookie as English or merge it with some optional struct perhaps or so, but since optional ("default") arguments are not available in Go, we should make another variation of `GetInventory()` I think, then we can maintain backward compatibility.  Maybe `GetInventoryDefaults()` or `GetInventoryInternal()`?

Also when you have time, Steam seems to start with count = 250 (always) then uses 75 for others, and start_assetid is not included, it's kind of important to do this as we need to mimic steam exactly.  Also check if TotalInventoryCount is below the chosen count and no need to return hasMore, just false.

Perhaps also figure out a way to pre-allocate the items array, or extend it each time, then use k + offset as the index (where offset is passed internally to `fetchInventory()` which is added with the returned item count).

**Comment by Furdarius** [comment]
@asamy Language was added in my previous pull request. In this PR only `filters` param break backward compatibility.

Is it right, you want to separate with two methods:
1) `GetInventoryDefaults(sid SteamID, appID, contextID uint64) (...)`
2) `GetInventory(sid SteamID, appID, contextID uint64, lang Lang, filters []Filter) (...)`

As I got, `start_assetid` sometimes included in inventory requests on official site. Are you sure that we can have problem with it?

steam_requests

**Comment by Furdarius** [comment]
It's strange to return `[]*InventoryItem` (array of pointers), so backward compatibility not fully fixed. But i guess it's better to change some code in your app, cuz it's really not effective return array of pointers.

**Comment by asamy** [comment]
Why is it strange?  It's not breaking backward compatibility this way, it was that way since forever.  If it's that bad, what do you suggest?

Also, language should default to English not none, as `Steam_Language` is set to English, and that's what the inventory method reflects to, so how about having some function to set language?  E.g.

```go
func (session *Session) SetLanguage(lang Lang) {
        session.lang = lang
}
```

`.lang` would also default to english.  See https://github.com/asamy/steam/blob/master/login.go#L200

**Comment by asamy** [comment]
The filter thing seems like an overkill, so I've decided to just stick with a bool, although filter seems a lot more flexible, however, if you still want to integrate this, then please use a separate branch and do the changes.

Sorry.

**Pull request closed without merging**
